## Switches
set_property PACKAGE_PIN V17 [get_ports {cmd[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cmd[0]}]
set_property PACKAGE_PIN V16 [get_ports {cmd[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {cmd[1]}]
# lr
set_property PACKAGE_PIN W16 [get_ports {lr}]
    set_property IOSTANDARD LVCMOS33 [get_ports {lr}]
# din
set_property PACKAGE_PIN W17 [get_ports {din[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property PACKAGE_PIN W15 [get_ports {din[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property PACKAGE_PIN V15 [get_ports {din[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property PACKAGE_PIN W14 [get_ports {din[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property PACKAGE_PIN W13 [get_ports {din[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
set_property PACKAGE_PIN V2 [get_ports {din[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
## LEDs
# dout_din
set_property PACKAGE_PIN U16 [get_ports {dout_din[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[0]}]
set_property PACKAGE_PIN E19 [get_ports {dout_din[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[1]}]
set_property PACKAGE_PIN U19 [get_ports {ldout_dined[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[2]}]
set_property PACKAGE_PIN V19 [get_ports {dout_din[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[3]}]
set_property PACKAGE_PIN W18 [get_ports {dout_din[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[4]}]
set_property PACKAGE_PIN U15 [get_ports {dout_din[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_din[5]}]

# dout_shifted
set_property PACKAGE_PIN U14 [get_ports {dout_shifted[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[0]}]
set_property PACKAGE_PIN V14 [get_ports {dout_shifted[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[1]}]
set_property PACKAGE_PIN V13 [get_ports {dout_shifted[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[2]}]
set_property PACKAGE_PIN V3 [get_ports {dout_shifted[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[3]}]
set_property PACKAGE_PIN W3 [get_ports {dout_shifted[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[4]}]
set_property PACKAGE_PIN U3 [get_ports {dout_shifted[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[5]}]
set_property PACKAGE_PIN P3 [get_ports {dout_shifted[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {dout_shifted[6]}]

##7 segment display
# set_property PACKAGE_PIN W7 [get_ports {y[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]
# set_property PACKAGE_PIN W6 [get_ports {y[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
# set_property PACKAGE_PIN U8 [get_ports {y[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
# set_property PACKAGE_PIN V8 [get_ports {y[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]
# set_property PACKAGE_PIN U5 [get_ports {y[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}]
# set_property PACKAGE_PIN V5 [get_ports {y[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}]
# set_property PACKAGE_PIN U7 [get_ports {y[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}]
#set_property PACKAGE_PIN V7 [get_ports dp]
#set_property IOSTANDARD LVCMOS33 [get_ports dp]
## ANOD
# set_property PACKAGE_PIN U2 [get_ports {an[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
# set_property PACKAGE_PIN U4 [get_ports {an[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
# set_property PACKAGE_PIN V4 [get_ports {an[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
# set_property PACKAGE_PIN W4 [get_ports {an[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]